### ISSUE TITLE
v1.0.0.14 checklist

### ISSUE THREAD

**Issue by jspenguin2017** [NanoAdblocker/NanoCore#50]
- [x] Test https://github.com/NanoAdblocker/NanoCore/issues/49
 - [x] Test https://github.com/NanoAdblocker/NanoCore/issues/44
 - [x] Fix https://github.com/NanoAdblocker/NanoCore/issues/46
 - [x] Update assets, version, and package
